server:
  port: 8111
  servlet:
    context-path: /auth-server
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

swagger:
  enable: true

logging:
  level:
    # log 级别
    com.exercise: debug